def get_config(args):
    """Parameter configuration for datasets"""
    dataset_configs = {
        'synthetic3d': {
            "dataset": "synthetic3d",
            "lambda_1":0.1,
            "lambda_2":1.0,
            "epochs": 200,
            "lr": 3e-4,
            "batch_size": 1024,
            "hidden_dim": "256,512,1024",
            "z_dim": 32,
            "h_dim": 32,
            "shared_dim": 512,
            "tau": 0.5,
            "tau_g": 0.5,
            "weight_decay": 5e-6,
            "k_nn": 10,
            "n_init": 10,
            "gate_lr": 0.001,
            "seed": 42,
            "w_ema":0.999,
            "warmup":0,
        },
        'Mfeat': {
            "dataset": "Mfeat",
            "lambda_1":0.005,
            "lambda_2":50.0,
            "epochs": 200,
            "lr": 3e-4,
            "batch_size": 512,
            "hidden_dim": "256,512,1024",
            "z_dim": 32,
            "h_dim": 32,
            "shared_dim": 512,
            "tau": 0.05,
            "tau_g": 0.05,
            "weight_decay": 1e-6,
            "k_nn": 10,
            "n_init": 10,
            "gate_lr": 0.001,
            "seed": 42,
            "w_ema":0.999,
            "warmup":2,
        },
        'Fashion': {
            "dataset": "Fashion",
            "lambda_1":0.01,
            "lambda_2":50.0,
            "epochs": 200,
            "lr": 5e-4,
            "batch_size": 512,
            "hidden_dim": "1024,2048",
            "z_dim": 256,
            "h_dim": 256,
            "shared_dim": 512,
            "tau": 0.005,
            "tau_g": 0.005,
            "weight_decay": 5e-4,
            "k_nn": 20,
            "n_init": 20,
            "gate_lr": 0.005,
            "seed": 42,
            "w_ema":0.98,
            "warmup":1,
        },
        'Hdigit': {
            "dataset": "Hdigit",
            "lambda_1":0.01,
            "lambda_2":40.0,
            "epochs": 200,
            "lr": 1e-3,
            "batch_size": 512,
            "hidden_dim": "256,512,1024",
            "z_dim": 256,
            "h_dim": 256,
            "shared_dim": 512,
            "tau": 0.1,
            "tau_g": 0.1,
            "weight_decay": 5e-4,
            "k_nn": 20,
            "n_init": 20,
            "gate_lr": 0.0001,
            "seed": 42,
            "w_ema":0.98,
            "warmup":1,
        },
        'MNIST_USPS': {
            "dataset": "MNIST_USPS",
            "lambda_1":0.2,
            "lambda_2":40.0,
            "epochs": 200,
            "lr": 1e-3,
            "batch_size": 128,
            "hidden_dim": "1024,2048",
            "z_dim": 128,
            "h_dim": 128,
            "shared_dim": 512,
            "tau": 0.01,
            "tau_g": 0.01,
            "weight_decay": 1e-3,
            "k_nn": 20,
            "n_init": 20,
            "gate_lr": 0.001,
            "seed": 42,
            "w_ema":0.999,
            "warmup":0,            
        },
        'BDGP': {
            "--dataset": "BDGP",
            "lambda_1":0.001,
            "lambda_2":10.0,
            "epochs": 200,
            "lr": 3e-4,
            "batch_size": 256,
            "hidden_dim": "1024,2048",
            "z_dim": 32,
            "h_dim": 32,
            "shared_dim": 512,
            "tau": 0.005,
            "tau_g": 0.005,
            "weight_decay": 1e-4,
            "k_nn": 20,
            "n_init": 20,
            "gate_lr": 0.001,
            "seed": 42,
            "w_ema":0.999,
            "warmup":0,
        }
    }
        
    # Update args with dataset-specific config
    config = dataset_configs[args.dataset]
    for key, value in config.items():
        setattr(args, key, value)
            
    return args
